title: Digital suverænitet i praksis
description: Annas specialeforberedende forløb hos OS2 – undersøgelse af digital suverænitet i praksis.
theme: just-the-docs

mermaid:
  version: "11.17.0"


url: https://just-the-docs.github.io

aux_links:
  Link til repository: https://github.com/anna-leland/digi-suveraenitet-i-praksis
  
defaults:
  - scope:
      path: ""         # alle filer i hele repository'et
      type: "pages"    # markdown-sider
    values:
      layout: "default"
      has_toc: false   # fjerner overordnet "Table of contents". Sæt til true her eller i headeren på de enkelte sider.

exclude:
  - docs/os2forloeb2026/Interviews/
  - docs/os2forloeb2026/Onboardingmoeder/